/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nurcan
 */
public class moduller extends javax.swing.JFrame {

    /**
     * Creates new form moduller
     */
    public moduller() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        camasirhane = new javax.swing.JButton();
        yemekhanebtn = new javax.swing.JButton();
        etutodalaribtn = new javax.swing.JButton();
        izinbtn = new javax.swing.JButton();
        bosodalar = new javax.swing.JButton();
        ulasimaracsaatleri = new javax.swing.JButton();
        dilekistekbtn = new javax.swing.JButton();
        duyurularbtn = new javax.swing.JButton();
        sosyaletkinlikbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        camasirhane.setBackground(new java.awt.Color(153, 255, 153));
        camasirhane.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        camasirhane.setText("ÇAMAŞIRHANE ");
        camasirhane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camasirhaneActionPerformed(evt);
            }
        });

        yemekhanebtn.setBackground(new java.awt.Color(153, 255, 153));
        yemekhanebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yemekhanebtn.setText("YEMEKHANE");
        yemekhanebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yemekhanebtnActionPerformed(evt);
            }
        });

        etutodalaribtn.setBackground(new java.awt.Color(153, 255, 153));
        etutodalaribtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etutodalaribtn.setText("ETÜT ODALARI");
        etutodalaribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etutodalaribtnActionPerformed(evt);
            }
        });

        izinbtn.setBackground(new java.awt.Color(153, 255, 153));
        izinbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        izinbtn.setText("İZİN ALMA");
        izinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izinbtnActionPerformed(evt);
            }
        });

        bosodalar.setBackground(new java.awt.Color(153, 255, 153));
        bosodalar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bosodalar.setText("BOŞ ODALAR");
        bosodalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosodalarActionPerformed(evt);
            }
        });

        ulasimaracsaatleri.setBackground(new java.awt.Color(153, 255, 153));
        ulasimaracsaatleri.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ulasimaracsaatleri.setText("ULAŞIM  SAATLERİ");
        ulasimaracsaatleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulasimaracsaatleriActionPerformed(evt);
            }
        });

        dilekistekbtn.setBackground(new java.awt.Color(153, 255, 153));
        dilekistekbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dilekistekbtn.setText("DİLEK-İSTEK");
        dilekistekbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dilekistekbtnActionPerformed(evt);
            }
        });

        duyurularbtn.setBackground(new java.awt.Color(153, 255, 153));
        duyurularbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        duyurularbtn.setText("DUYURULAR");
        duyurularbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duyurularbtnActionPerformed(evt);
            }
        });

        sosyaletkinlikbtn.setBackground(new java.awt.Color(153, 255, 153));
        sosyaletkinlikbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sosyaletkinlikbtn.setText("SOSYAL ETKİNLİKLER");
        sosyaletkinlikbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sosyaletkinlikbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BATTALGAZİ KIZ ÖĞRENCİ YURDU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(izinbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yemekhanebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etutodalaribtn, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(duyurularbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sosyaletkinlikbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(camasirhane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ulasimaracsaatleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dilekistekbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bosodalar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duyurularbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bosodalar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yemekhanebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sosyaletkinlikbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ulasimaracsaatleri, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etutodalaribtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dilekistekbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camasirhane, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etutodalaribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etutodalaribtnActionPerformed
        // TODO add your handling code here:
        etutodalari eo = new etutodalari();
        eo.setVisible(true);
    }//GEN-LAST:event_etutodalaribtnActionPerformed

    private void yemekhanebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yemekhanebtnActionPerformed
        // TODO add your handling code here:
        yemekhane ym=new yemekhane();
        ym.setVisible(true);
    }//GEN-LAST:event_yemekhanebtnActionPerformed

    private void camasirhaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camasirhaneActionPerformed
        // TODO add your handling code here:
        camasirhane c = new camasirhane();
        c.setVisible(true);
    }//GEN-LAST:event_camasirhaneActionPerformed

    private void ulasimaracsaatleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulasimaracsaatleriActionPerformed
        ulasim u = new ulasim();
        u.setVisible(true);
    }//GEN-LAST:event_ulasimaracsaatleriActionPerformed

    private void izinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izinbtnActionPerformed
        // TODO add your handling code here:
        izinalma i = new izinalma();
        i.setVisible(true);
    }//GEN-LAST:event_izinbtnActionPerformed

    private void dilekistekbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dilekistekbtnActionPerformed
        dilekistek di =new dilekistek();
        di.setVisible(true);
    }//GEN-LAST:event_dilekistekbtnActionPerformed

    private void duyurularbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duyurularbtnActionPerformed
        // TODO add your handling code here:
        duyurularogrenci duyuru = new duyurularogrenci();
        duyuru.setVisible(true);
    }//GEN-LAST:event_duyurularbtnActionPerformed

    private void sosyaletkinlikbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sosyaletkinlikbtnActionPerformed
       sosyaletkinlik se= new sosyaletkinlik();
       se.setVisible(true);
        
    }//GEN-LAST:event_sosyaletkinlikbtnActionPerformed

    private void bosodalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosodalarActionPerformed
        bosOda oda= new bosOda();
        oda.setVisible(true);
    }//GEN-LAST:event_bosodalarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(moduller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(moduller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(moduller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(moduller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new moduller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bosodalar;
    private javax.swing.JButton camasirhane;
    private javax.swing.JButton dilekistekbtn;
    private javax.swing.JButton duyurularbtn;
    private javax.swing.JButton etutodalaribtn;
    private javax.swing.JButton izinbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sosyaletkinlikbtn;
    private javax.swing.JButton ulasimaracsaatleri;
    private javax.swing.JButton yemekhanebtn;
    // End of variables declaration//GEN-END:variables
}
